/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ly_ndk_module_SayHello */

#ifndef _Included_com_ly_ndk_module_SayHello
#define _Included_com_ly_ndk_module_SayHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ly_ndk_module_SayHello
 * Method:    getHelloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ly_ndk_module_SayHello_getHelloFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
